// <auto-generated />
namespace Akıllı_Etkinlik_Planlama_Platformu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class deneme01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deneme01));
        
        string IMigrationMetadata.Id
        {
            get { return "202411101619589_deneme01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
