// <auto-generated />
namespace Akıllı_Etkinlik_Planlama_Platformu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddCompositeKeyToKatilimcilar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCompositeKeyToKatilimcilar));
        
        string IMigrationMetadata.Id
        {
            get { return "202502161504397_AddCompositeKeyToKatilimcilar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
